#spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test_security
spring.datasource.username=postgres
spring.datasource.password=2529062k3

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect